use rand::Rng;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use tauri::AppHandle;

use crate::modules::common::path::{expand_home, hive_projects_dir};
use crate::modules::common::utils::setup_path;

use super::config::{
    AdminConfig, CreateWordPressRequest, DatabaseConfig, SiteConfig, WordPressConfig,
    WordPressProject, WordPressResponse,
};
use super::download::{download_and_extract_wordpress, get_github_zip_url};

/// Sanitizes a project name for use as a filesystem segment. Rejects anything
/// that could traverse directories (`/`, `\`, `..`) or hide files.
fn sanitize_project_name(name: &str) -> Result<String, String> {
    let trimmed = name.trim();
    if trimmed.is_empty() {
        return Err("Project name cannot be empty".to_string());
    }
    if trimmed == "." || trimmed == ".." || trimmed.contains('/') || trimmed.contains('\\') {
        return Err(format!("Invalid project name '{}'", name));
    }
    Ok(trimmed.to_string())
}

fn generate_secure_password() -> String {
    const CHARSET: &[u8] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?";

    let mut rng = rand::thread_rng();
    let password: String = (0..32)
        .map(|_| {
            let idx = rng.gen_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect();

    password
}

fn generate_salts() -> String {
    let salt_names = [
        "AUTH_KEY",
        "SECURE_AUTH_KEY",
        "LOGGED_IN_KEY",
        "NONCE_KEY",
        "AUTH_SALT",
        "SECURE_AUTH_SALT",
        "LOGGED_IN_SALT",
        "NONCE_SALT",
    ];

    let mut salts = String::new();
    for name in salt_names.iter() {
        salts.push_str(&format!(
            "define('{}', '{}');\n",
            name,
            generate_secure_password()
        ));
    }
    salts
}

fn generate_wp_config(project_path: &Path, request: &CreateWordPressRequest) -> Result<(), String> {
    let db_password = if request.db_password.is_empty() {
        generate_secure_password()
    } else {
        request.db_password.clone()
    };

    let salt_keys = generate_salts();

    let config_content = format!(
        r#"<?php
/**
 * WordPress configuration generated by Hive
 */

// Database settings
define('DB_NAME', '{}');
define('DB_USER', '{}');
define('DB_PASSWORD', '{}');
define('DB_HOST', '{}:{}');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

// Authentication salts
{}

// Table prefix
$table_prefix = 'wp_';

// Development settings
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);

// Site URL
define('WP_HOME', '{}');
define('WP_SITEURL', '{}');

// Admin email
define('ADMIN_EMAIL', '{}');

// Disable automatic updates
define('AUTOMATIC_UPDATER_DISABLED', true);

// Increase memory limit
define('WP_MEMORY_LIMIT', '256M');
define('WP_MAX_MEMORY_LIMIT', '512M');

// Abort
if (!defined('ABSPATH')) {{
    define('ABSPATH', __DIR__ . '/');
}}

// Include settings
require_once ABSPATH . 'wp-settings.php';
"#,
        request.db_name,
        request.db_user,
        db_password,
        request.db_host,
        request.db_port,
        salt_keys,
        request.site_url,
        request.site_url,
        request.admin_email
    );

    let config_path = project_path.join("wp-config.php");
    fs::write(&config_path, config_content)
        .map_err(|e| format!("Failed to write wp-config.php: {}", e))?;

    Ok(())
}

fn generate_env_file(project_path: &Path, request: &CreateWordPressRequest) -> Result<(), String> {
    let admin_password = request
        .admin_password
        .clone()
        .unwrap_or_else(generate_secure_password);

    let env_content = format!(
        r#"# WordPress Environment Configuration
PROJECT_NAME={}
WP_VERSION={}
WP_HOME={}
WP_SITEURL={}
DB_NAME={}
DB_USER={}
DB_PASSWORD={}
DB_HOST={}
DB_PORT={}
ADMIN_USER={}
ADMIN_PASSWORD={}
ADMIN_EMAIL={}
SITE_TITLE={}
PORT={}
HOST={}
"#,
        request.name,
        request.version,
        request.site_url,
        request.site_url,
        request.db_name,
        request.db_user,
        request.db_password,
        request.db_host,
        request.db_port,
        request.admin_user,
        admin_password,
        request.admin_email,
        request.site_title,
        request.port,
        request.host
    );

    let env_path = project_path.join(".env");
    fs::write(&env_path, env_content).map_err(|e| format!("Failed to write .env: {}", e))?;

    Ok(())
}

fn save_project_metadata(project_path: &Path, project: &WordPressProject) -> Result<(), String> {
    let metadata = serde_json::to_string_pretty(project)
        .map_err(|e| format!("Failed to serialize metadata: {}", e))?;

    let metadata_path = project_path.join(".hive-project");
    fs::write(&metadata_path, metadata).map_err(|e| format!("Failed to write metadata: {}", e))?;

    Ok(())
}

/// Register the WordPress project in Hive's central registry
/// (`~/.hive/projects/<name>.json`) so it appears in the projects list and the
/// detail view can read its properties.
fn register_project(project: &WordPressProject) -> Result<(), String> {
    let hive_dir = hive_projects_dir();
    fs::create_dir_all(&hive_dir)
        .map_err(|e| format!("Failed to create Hive projects directory: {}", e))?;

    // The name becomes a filename segment (`~/.hive/projects/<name>.json`);
    // reject anything that could escape the registry directory.
    sanitize_project_name(&project.name)?;

    let uuid = uuid::Uuid::new_v4().to_string();
    let project_info = serde_json::json!({
        "id": uuid,
        "name": project.name,
        "type": "wordpress",
        "path": project.path,
        "description": project.description,
        "created_at": chrono::Local::now().to_rfc3339(),
        "version": project.config.version,
        "host": project.config.host,
        "port": project.config.port,
        "source_type": project.source_type,
        "dbDriver": project.config.database.driver,
        "dbName": project.config.database.name,
        "dbUser": project.config.database.user,
        "dbHost": project.config.database.host,
        "dbPort": project.config.database.port,
        "siteTitle": project.config.site.title,
        "siteUrl": project.config.site.url,
        "adminUser": project.config.admin.user,
        "adminEmail": project.config.admin.email,
    });

    let project_file = hive_dir.join(format!("{}.json", project.name));

    fs::write(
        &project_file,
        serde_json::to_string_pretty(&project_info)
            .map_err(|e| format!("Failed to serialize project metadata: {}", e))?,
    )
    .map_err(|e| format!("Failed to save project metadata: {}", e))?;

    Ok(())
}

async fn download_from_wordpress_org(
    project_path: &Path,
    request: &CreateWordPressRequest,
) -> Result<(), String> {
    let version = if request.version == "latest" {
        "".to_string()
    } else {
        format!("wordpress-{}", request.version)
    };

    let url = if version.is_empty() {
        "https://wordpress.org/latest.zip".to_string()
    } else {
        format!("https://wordpress.org/{}.zip", version)
    };

    download_and_extract_wordpress(project_path, &url).await
}

async fn clone_from_github(
    project_path: &Path,
    request: &CreateWordPressRequest,
) -> Result<(), String> {
    let repo = request
        .github_repo
        .clone()
        .unwrap_or_else(|| "https://github.com/WordPress/WordPress".to_string());

    let mut cmd = Command::new("git");
    cmd.arg("clone");

    if let Some(branch) = &request.github_branch {
        if !branch.is_empty() {
            cmd.arg("--branch").arg(branch);
        }
    }

    cmd.arg(&repo).arg(project_path);

    setup_path(&mut cmd);

    let output = cmd
        .output()
        .map_err(|e| format!("Failed to execute git clone: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("Git clone failed: {}", stderr));
    }

    Ok(())
}

async fn download_from_github_zip(
    project_path: &Path,
    request: &CreateWordPressRequest,
) -> Result<(), String> {
    let url = if let Some(custom_url) = &request.github_zip_url {
        if !custom_url.is_empty() {
            custom_url.clone()
        } else {
            get_github_zip_url(&request.version).await?
        }
    } else {
        get_github_zip_url(&request.version).await?
    };

    download_and_extract_wordpress(project_path, &url).await
}

/// Returns true when the directory contains no entries.
fn is_dir_empty(path: &Path) -> bool {
    match fs::read_dir(path) {
        Ok(mut entries) => entries.next().is_none(),
        Err(_) => false,
    }
}

/// Returns true when the directory looks like an existing WordPress
/// installation. We look for core loader files that are always present in a
/// real install (`wp-load.php` / `wp-settings.php`).
fn is_wordpress_install(path: &Path) -> bool {
    path.join("wp-load.php").exists() || path.join("wp-settings.php").exists()
}

/// Best-effort detection of the installed WordPress version by reading
/// `wp-includes/version.php`. Returns `None` when it cannot be determined.
fn detect_wordpress_version(path: &Path) -> Option<String> {
    let version_file = path.join("wp-includes").join("version.php");
    let content = fs::read_to_string(version_file).ok()?;
    for line in content.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("$wp_version") {
            if let Some(eq) = rest.find('=') {
                let value = rest[eq + 1..]
                    .trim()
                    .trim_matches('\'')
                    .trim_matches('"')
                    .trim_end_matches(';')
                    .trim();
                if !value.is_empty() {
                    return Some(value.to_string());
                }
            }
        }
    }
    None
}

#[tauri::command]
pub async fn create_wordpress_project(
    _app: AppHandle,
    request: CreateWordPressRequest,
) -> Result<WordPressResponse, String> {
    // Default WordPress install location is ~/Projects (a user-facing
    // convention), distinct from Hive's internal ~/.hive/projects.
    let projects_dir = crate::modules::common::path::home_dir().join("Projects");

    // Respect an explicit installation path when provided, otherwise fall back
    // to ~/Projects/<name>.
    let project_path = if let Some(wp_path) = &request.wp_path {
        if !wp_path.trim().is_empty() {
            PathBuf::from(expand_home(wp_path.trim()))
        } else {
            projects_dir.join(&request.name)
        }
    } else {
        projects_dir.join(&request.name)
    };

    // Decide how to handle a pre-existing target directory.
    let dir_pre_existed = project_path.exists();
    let existing_wp = dir_pre_existed && is_wordpress_install(&project_path);
    let dir_empty = dir_pre_existed && project_path.is_dir() && is_dir_empty(&project_path);

    if dir_pre_existed && !existing_wp && !dir_empty {
        return Ok(WordPressResponse {
            success: false,
            message: "Directory is not empty".to_string(),
            project: None,
            error: Some(format!(
                "Directory {} already exists and does not contain a WordPress installation. Choose an empty directory or an existing WordPress site.",
                project_path.display()
            )),
        });
    }

    // Create the directory only when it does not already exist.
    if !dir_pre_existed {
        if let Err(e) = fs::create_dir_all(&project_path) {
            return Err(format!("Failed to create directory: {}", e));
        }
    }

    // In import mode (an existing WordPress site) we skip downloading and
    // extracting WordPress, as well as generating wp-config.php which the site
    // already owns.
    if !existing_wp {
        let result = match request.source_type.as_str() {
            "wordpress_org" => download_from_wordpress_org(&project_path, &request).await,
            "github_clone" => clone_from_github(&project_path, &request).await,
            "github_zip" => download_from_github_zip(&project_path, &request).await,
            _ => Err("Invalid source type".to_string()),
        };

        if let Err(e) = result {
            // Only remove the directory if we created it ourselves; never delete
            // a directory the user already had on disk.
            if !dir_pre_existed {
                let _ = fs::remove_dir_all(&project_path);
            }
            return Ok(WordPressResponse {
                success: false,
                message: "Failed to create project".to_string(),
                project: None,
                error: Some(e),
            });
        }

        if let Err(e) = generate_wp_config(&project_path, &request) {
            if !dir_pre_existed {
                let _ = fs::remove_dir_all(&project_path);
            }
            return Ok(WordPressResponse {
                success: false,
                message: "Failed to generate wp-config.php".to_string(),
                project: None,
                error: Some(e),
            });
        }
    }

    if let Err(e) = generate_env_file(&project_path, &request) {
        if !dir_pre_existed {
            let _ = fs::remove_dir_all(&project_path);
        }
        return Ok(WordPressResponse {
            success: false,
            message: "Failed to generate .env file".to_string(),
            project: None,
            error: Some(e),
        });
    }

    // For an imported site, prefer the actually installed version when we can
    // detect it, falling back to the requested version.
    let resolved_version = if existing_wp {
        detect_wordpress_version(&project_path).unwrap_or_else(|| request.version.clone())
    } else {
        request.version.clone()
    };

    let project = WordPressProject {
        name: request.name.clone(),
        path: project_path.to_string_lossy().to_string(),
        description: request.description.clone().unwrap_or_else(|| {
            if existing_wp {
                format!("Imported WordPress {} site", resolved_version)
            } else {
                format!("WordPress {} site", resolved_version)
            }
        }),
        source_type: if existing_wp {
            "import".to_string()
        } else {
            request.source_type.clone()
        },
        config: WordPressConfig {
            port: request.port,
            host: request.host.clone(),
            version: resolved_version,
            database: DatabaseConfig {
                driver: request.db_driver.clone(),
                host: request.db_host.clone(),
                port: request.db_port,
                name: request.db_name.clone(),
                user: request.db_user.clone(),
            },
            site: SiteConfig {
                title: request.site_title.clone(),
                url: request.site_url.clone(),
            },
            admin: AdminConfig {
                user: request.admin_user.clone(),
                email: request.admin_email.clone(),
            },
        },
    };

    if let Err(e) = save_project_metadata(&project_path, &project) {
        return Ok(WordPressResponse {
            success: false,
            message: "Failed to save metadata".to_string(),
            project: None,
            error: Some(e),
        });
    }

    // Register the project in Hive's central registry so it shows up in the
    // projects list and the detail view can read its properties.
    if let Err(e) = register_project(&project) {
        return Ok(WordPressResponse {
            success: false,
            message: "Failed to register project".to_string(),
            project: None,
            error: Some(e),
        });
    }

    let message = if existing_wp {
        "Existing WordPress site imported successfully".to_string()
    } else {
        "WordPress site created successfully".to_string()
    };

    Ok(WordPressResponse {
        success: true,
        message,
        project: Some(project),
        error: None,
    })
}
